### PR TITLE
created a class named Ali

### PR DESCRIPTION
**Pull request by aliakpa**
Can you check if everything is good?

### CODE REVIEW

**Comment by VictorIachim** [comment]
good

**Comment by MustafaOk** [comment]
could you please fix the line X and push it again

**Comment by VictorIachim** [comment]
> could you please fix the line X and push it again

if you need changes... make them yourself

**Comment by MustafaOk** [comment]
> > could you please fix the line X and push it again
> 
> if you need changes... make them yourself

then why did I hire you?

**Comment by aliakpa** [comment]
> > > could you please fix the line X and push it again
> > 
> > 
> > if you need changes... make them yourself
> 
> then why did I hire you?
It is working. keep professional :)

**Comment by Aidana1202** [comment]
wow code looks great😂

**Comment by MustafaOk** [comment]
okey everything looks good now. Thank you Ali. (I am closing this PR)

**Comment by aliakpa** [comment]
Somebody  merge it ? I don't want to it myself :)

**Comment by IgorTirsina** [comment]
Lets do it!

**Pull request merged**
