### PR TITLE
Victor 7 7 2021 - Finish the test case for TC501

### PR DESCRIPTION
**Pull request by VictorIachim**
Added this code there
And this code here
Added code everywhere

### CODE REVIEW

**Comment by Aidana1202** [comment]
Nice Coding Skills 😂

**Comment by VictorIachim** [comment]
> Nice Coding Skills 😂

I did my best. But can do better 💯

**Review by MustafaOk — COMMENTED** [review]
aaaaggghsim

**Review by MustafaOk — APPROVED** [review]
interesting

**Comment by aliakpa** [comment]
nice work. Needs improvement though :)

**Pull request merged**
