### PR TITLE
day2withGorup

### PR DESCRIPTION
**Pull request by akachenia**
added new local branch
 and folder

### CODE REVIEW

**Review by MustafaOk — COMMENTED** [review]
i liked it

**Comment by MustafaOk** [comment]
liked it

**Comment by Aidana1202** [comment]
Good job 👏

**Comment by akachenia** [comment]
Thank u team

**Comment by MustafaOk** [comment]
cool

**Review by VictorIachim — APPROVED** [review]
I approve it for now. Make sure you do more than 100%

**Comment by akachenia** [comment]
Thank u Victor

**Pull request merged**
