### PR TITLE
Gulnaz2nd branch

### PR DESCRIPTION
**Pull request by gbayalinova**
Hi guys! Please review my second commit :)

### CODE REVIEW

**Comment by IgorTirsina** [comment]
> Hi guys! Please review my second commit :)

Hey Gulnaz. everything looks great.

**Comment by IgorTirsina** [comment]
> > Hi guys! Please review my second commit :)
> 
> Hey Gulnaz. everything looks great.

Also Gulnaz, i think you need to add *.iml in your .gitignore file, so we dont need to see those files.

**Comment by IgorTirsina** [comment]
> > > Hi guys! Please review my second commit :)
> > 
> > 
> > Hey Gulnaz. everything looks great.
> 
> Also Gulnaz, i think you need to add *.iml in your .gitignore file, so we dont need to see those files.

image

**Comment by m-abdurahman** [comment]
Gulnaz, great job!

**Comment by Aidana1202** [comment]
Nice code!!!

**Comment by akachenia** [comment]
Good job Gulnaz!

**Review by VictorIachim — APPROVED** [review]
Please make changes there and here
and everywhere
but after I approve it

**Review by m-abdurahman — APPROVED** [review]
Good job!

**Review by Aidana1202 — APPROVED** [review]

**Pull request merged**
