### PR TITLE
This is an expected conflict with Igoriok

### PR DESCRIPTION
**Pull request by VictorIachim**
Bojour

### CODE REVIEW

**Comment by akachenia** [comment]
this is a clean code ))

**Review by IgorTirsina — COMMENTED** [review]
Lets keep calm, and code Java

**Comment by VictorIachim** [comment]
> this is a clean code ))

but has a cinflict
please check on that

**Comment by akachenia** [comment]
oh i see it now

**Comment by akachenia** [comment]
oh i see it now

**Review by aliakpa — APPROVED** [review]

**Comment by IgorTirsina** [comment]
We decided to keep both lines of code

**Pull request merged**
